version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poetry-kafka-producer
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka
    volumes:
      - .:/app # Optional: Mount the project directory for real-time development.

networks:
  kafka:
    external: true
