services:
  data-collection:
    image: docker.czumpers.com/cs-data-collection:test
    container_name: cs-data-collection-test
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      JOKES_URL: https://v2.jokeapi.dev/joke/Any
      ONE_PART_JOKES_TOPIC: one-part-jokes
      TWO_PART_JOKES_TOPIC: two-part-jokes
      DAILY_TRIVIA_URL: https://www.reddit.com/r/todayilearned/.rss
      DAILY_TRIVIA_TOPIC: daily-trivia
      TIMEOUT: 5
      ERROR_WAIT_TIME: 180
    networks:
      - kafka-test
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cs-data-collection-test.rule=Host(`api-test.czumpers.com`) && PathPrefix(`/api/v1/data-collection`)"
      - "traefik.http.routers.cs-data-collection-test.entrypoints=websecure"
      - "traefik.http.routers.cs-data-collection-test.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  kafka-test:
    external: true
  traefik-public:
    external: true
