services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poetry-kafka-producer
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      JOKES_URL: https://v2.jokeapi.dev/joke/Any
      ONE_PART_JOKES_TOPIC: one-part-jokes
      TWO_PART_JOKES_TOPIC: two-part-jokes
      DAILY_TRIVIA_URL: https://www.reddit.com/r/todayilearned/.rss
      DAILY_TRIVIA_TOPIC: daily-trivia
      TIMEOUT: 5
      ERROR_WAIT_TIME: 180
    ports:
      - "8000:8000"
    networks:
      - kafka
    volumes:
      - .:/app

networks:
  kafka:
    external: true
