version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_GITHUB_TOKEN=${GF_GITHUB_TOKEN}
    volumes:
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
      - ./custom.ini:/etc/grafana/grafana.ini 
    ports:
      - "3000:3000"
    networks:
      # - grafana-network
      - shared-network
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  # grafana-network:
  #   driver: bridge
  shared-network:
    external: true 
