version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Maps Grafana's default port 3000 to your local machine
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Default admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password
    volumes:
      - grafana-data:/var/lib/grafana  # Persist data in a named volume


volumes:
  grafana-data: