version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS} #TODO plugins here or in env?
      - GF_GITHUB_TOKEN=${GF_GITHUB_TOKEN}
    volumes:
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000" #TODO check if ports are free ( other services )
    networks:
      - grafana-network
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  grafana-network:
    driver: bridge