
services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_GITHUB_TOKEN=${GF_GITHUB_TOKEN}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=...
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - grafana-network
      - vault

    restart: unless-stopped
    entrypoint: >
      /bin/bash -c "
        export GF_SECURITY_ADMIN_PASSWORD=\$(curl --silent --header 'X-Vault-Token: ...' http://vault:8200/v1/secret/data/grafana/config | jq -r '.data.data.GF_SECURITY_ADMIN_PASSWORD') && \
        echo 'GF_SECURITY_ADMIN_PASSWORD=\$GF_SECURITY_ADMIN_PASSWORD' && \
        /run.sh
      "

volumes:
  grafana-storage:

networks:
  grafana-network:
    driver: bridge
  vault:
    external: true
