services:
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    container_name: kafka-test
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "fajnioASFAIHU83982fas"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-test

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui-test
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      AUTH_TYPE: "LOGIN_FORM"
    env_file:
      - ".env"
    depends_on:
      - kafka
    networks:
      - traefik-public
      - kafka-test
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kafka-ui-test.rule=Host(`kafka-test.czumpers.com`)"
      - "traefik.http.routers.kafka-ui-test.entrypoints=websecure"
      - "traefik.http.routers.kafka-ui-test.tls.certresolver=myresolver"

networks:
  kafka-test:
    name: kafka-test
  traefik-public:
    external: true

volumes:
  kafka-data:
