services:
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka
    container_name: kafka-test
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "fajnioASFAIHU83982fas"
    restart: unless-stopped
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-test

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui-test
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: ${KAFKA_UI_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASSWORD}
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - traefik-public
      - kafka-test
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kafka-ui-test.rule=Host(`kafka-test.czumpers.com`)"
      - "traefik.http.routers.kafka-ui-test.entrypoints=websecure"
      - "traefik.http.routers.kafka-ui-test.tls.certresolver=myresolver"

  elasticsearch:
    image: elasticsearch:8.15.5
    container_name: elasticsearch-test
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - server.publicBaseUrl=https://kibana-test.czumpers.com
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elknet-test

  kibana:
    image: kibana:8.15.5
    container_name: kibana-test
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    restart: unless-stopped
    networks:
      - elknet-test
      - traefik-public
    depends_on:
      - elasticsearch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana-test.rule=Host(`kibana-test.czumpers.com`)"
      - "traefik.http.routers.kibana-test.entrypoints=websecure"
      - "traefik.http.routers.kibana-test.tls.certresolver=myresolver"

networks:
  kafka-test:
    name: kafka-test
  elknet-test:
    name: elknet-test
  traefik-public:
    external: true

volumes:
  kafka-data:
  elasticsearch-data:
