services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - search

  data-search:
    build:
      context: ../../CzumperSearch/data_search
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - elknet
      - search
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_ELASTICSEARCH_HOST: elasticsearch

networks:
  search:
    external: false
  elknet:
    external: true