
services:
  data_storage_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: data_storage_service

    networks:
      - kafka
      - elknet
      - shared-network
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ELASTICSEARCH_URL: http://elasticsearch:9200

networks:
  kafka:
    external: true
    driver: local
  elknet:
    external: true
  shared-network:
    external: true

