[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Mateusz <01178563@pw.edu.pl>"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.10"
kafka = "^1.3.5"
elasticsearch = "^8.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
