name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**/*"
      - "data_collection/**/*"
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.filter.outputs.frontend }}
      data-collection-changed: ${{ steps.filter.outputs.data_collection }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filter changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend: 
              - "frontend/**"
            data_collection:
              - "data_collection/**"

  deploy-frontend:
    if: ${{ needs.filter.outputs.frontend-changed == 'true' }}
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Custom Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/CzumperSearch/
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_URL }}/cs-frontend:test
            ${{ secrets.DOCKER_REGISTRY_URL }}/cs-frontend:${{ github.sha }}

  deploy-data-collection:
    if: ${{ needs.filter.outputs.data-collection-changed == 'true' }}
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Custom Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push data collection image
        uses: docker/build-push-action@v6
        with:
          context: ./data_collection
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_URL }}/cs-data-collection:test
            ${{ secrets.DOCKER_REGISTRY_URL }}/cs-data-collection:${{ github.sha }}
